"""Build audio metadata tags and embed cover art.

``build_tags`` produces an ffmpeg-compatible ``-metadata`` mapping (used at
encode time in :mod:`audiobook_forge.audio.encode`). ``embed_cover`` attaches
cover art *after* encoding using mutagen, which is the reliable cross-format way
to add artwork to MP3 / MP4 (m4a) containers.
"""

from __future__ import annotations

from pathlib import Path

from ..core.domain import Book
from ..utils.logging import get_logger

logger = get_logger(__name__)


def build_tags(
    book: Book,
    track: int,
    track_total: int,
    chapter_title: str | None = None,
) -> dict[str, str]:
    """Return an ffmpeg metadata map for a chapter or single-file audiobook.

    Args:
        book: The parsed book (title/author/language).
        track: 1-based track number (chapter index, or 1 for a single file).
        track_total: Total number of tracks.
        chapter_title: Optional per-track title. Falls back to the book title.

    Returns:
        A dict of tag name -> value. Empty values are dropped by the encoder.
    """
    title = chapter_title or book.title
    tags: dict[str, str] = {
        "title": title,
        "artist": book.author or "Unknown",
        "album_artist": book.author or "Unknown",
        "album": book.title,
        "track": f"{track}/{track_total}",
        "genre": "Audiobook",
        "comment": "Generated by Audiobook Forge",
    }
    if book.language:
        tags["language"] = book.language
    return tags


def embed_cover(audio_path: Path, cover_path: Path) -> None:
    """Embed ``cover_path`` (JPEG) into ``audio_path`` when the format supports it.

    Best-effort: unsupported containers (wav/opus/aac streams) are skipped with a
    debug log rather than failing the conversion.
    """
    if not cover_path.exists():
        return
    suffix = audio_path.suffix.lower()
    try:
        if suffix == ".mp3":
            _embed_mp3(audio_path, cover_path)
        elif suffix in {".m4a", ".mp4", ".aac"}:
            _embed_mp4(audio_path, cover_path)
        else:
            logger.debug("Cover embedding not supported for %s", suffix)
    except Exception as exc:  # pragma: no cover - non-fatal
        logger.warning("Could not embed cover into %s: %s", audio_path.name, exc)


def _embed_mp3(audio_path: Path, cover_path: Path) -> None:
    from mutagen.id3 import APIC, ID3, ID3NoHeaderError

    try:
        tags = ID3(audio_path)
    except ID3NoHeaderError:
        tags = ID3()
    tags.delall("APIC")
    tags.add(
        APIC(
            encoding=3,
            mime="image/jpeg",
            type=3,  # front cover
            desc="Cover",
            data=cover_path.read_bytes(),
        )
    )
    tags.save(audio_path)


def _embed_mp4(audio_path: Path, cover_path: Path) -> None:
    from mutagen.mp4 import MP4, MP4Cover

    audio = MP4(audio_path)
    audio["covr"] = [MP4Cover(cover_path.read_bytes(), imageformat=MP4Cover.FORMAT_JPEG)]
    audio.save()
